name: Github Push Mirror
on:
	push:
		branches:
			- '*'

jobs:
	push-mirror:
		runs-on: ubuntu-latest
		steps:
			- name: Checkout code
				run: git clone ${{ secrets.GITEAREPO }} .

			- name: Push Mirror
				run: git push --mirror ${{ secrets.GITHUBREPO }}
