name: Github Push Mirror
run-name: ${{ gitea.actor }} is pushing mirror to github
on: [push]

jobs:
  push-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Push Mirror
        run: git push --mirror ${{ secrets.GITHUBREPO }}
