name: Github Push Mirror
run-name: ${{ gitea.actor }} is pushing mirror to github
on: [push]

jobs:
  push-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: git clone ${{ secrets.GITEAREPO }} .

      - name: Add remote
        run: git remote add mirror https://ropoko:${{ secrets.GITEATOKEN }}@github.com/ropoko/ropoko.net.git

      - name: Push Mirror
        run: git push --verbose --mirror mirror

