name: Github Push Mirror
run-name: ${{ gitea.actor }} is pushing mirror to github
on: [push]

jobs:
  push-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: git clone ${{ secrets.GITEAREPO }} .

      - name: Go to repo
        run: cd ropoko.net/

      - name: Push Mirror
        run: git push --verbose --mirror ${{ secrets.GITHUBREPO }}
        env:
          USERNAME: ropoko
          GITHUB_TOKEN: ${{ secrets.GITEATOKEN }}
